spring:
  application:
    name: study-hub
  datasource:
    # 1. ?????localhost????3306????study_hub???
    url: jdbc:mysql://localhost:3306/study_hub?serverTimezone=Asia/Shanghai&characterEncoding=utf-8
    # 2. ??
    username: root
    # 3. ?? (?? ?????????????)
    password: "123456"
    # 4. ???
    driver-class-name: com.mysql.cj.jdbc.Driver